### ISSUE TITLE
Use Gradle instead of Maven

### ISSUE THREAD

**Issue by matiasvigil** [kevinvigil/billing-system#2]
Maven was the standard but in last 5 years [Gradle](https://gradle.org/) has become the one.

The best way to find what is the best version to use is by creating a new project with [Spring Initializer](https://start.spring.io/) and getting Gradle filed from it.

Once you move to Gradle try to use [toml file](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml).

**Comment by kevinvigil** [comment]
This is the toml file: [gradle/libs.versions.toml](https://github.com/kevinvigil/billing-system/blob/main/gradle/libs.versions.toml) 

And this is the build.gradle.kts: [build.gradle.kts](https://github.com/kevinvigil/billing-system/blob/main/build.gradle.kts)

Check this and telme if something could be better
